### ISSUE TITLE
Docker MD  (Hexo)

### ISSUE THREAD

**Issue by Anneryshc** [Anneryshc/is373_devops_hexo#10]
Docker information and links

**Comment by jar285** [comment]
### 1.1.1 Story 1 + Acceptance Criteria:
* As a student, I want to navigate easily to the Docker page from the main site so I can start learning about containerization.

**Acceptance Criteria:**

* A clear and visible link should be available in the main index that directs users to the Docker page.
* The link must work correctly and take the user to the appropriate page.

### 1.1.2 Story 2 + Acceptance Criteria:
* As a student, I want confirmation that I am on the Docker page by verifying key visual indicators.

**Acceptance Criteria:**

* The page title in the browser tab should include "Docker Setup."
* The page heading should clearly display "Docker."
* The page content should start with a brief introduction to Docker and its significance.
