### ISSUE TITLE
Containerization vs Virtualization MD (Hexo)

### ISSUE THREAD

**Issue by Anneryshc** [Anneryshc/is373_devops_hexo#12]
Add links and information

**Comment by jar285** [comment]
## 1.2 Epic 2: Containerization vs Virtualization + Criteria
### 1.2.1 Story 1 + Criteria:
* As a student, I want to be able to access the Containerization vs Virtualization page from the glossary.

**Acceptance Criteria:**

* The glossary should have a working link that leads to the Containerization vs Virtualization page.
* The link must be visible and functional.

### 1.2.2 Story 2 + Criteria:
* As a student, I want to verify that the page content is correct for Containerization vs Virtualization.

**Acceptance Criteria:**

* The page title should be “Containerization vs Virtualization.”
* The page heading must read “Containerization vs Virtualization.”
* Key concepts like “Containerization” and “Virtualization” must be visible and explained.
