### ISSUE TITLE
 Kubernetes vs Docker MD (Hexo)

### ISSUE THREAD

**Issue by Anneryshc** [Anneryshc/is373_devops_hexo#13]
Add links and information.

**Comment by jar285** [comment]
## 1.10 Epic 10: Kubernetes vs Docker + Criteria
### 1.10.1 Story 1 + Criteria:

- As a student, I want to access the Kubernetes vs Docker page from the main index to understand the differences between container orchestration and container management.

**Acceptance Criteria:**

- A clearly visible and functional link should be available in the main index or glossary directing users to the Kubernetes vs Docker page.

- The link must take the user to the correct page.


### 1.10.2 Story 2 + Criteria:

- As a student, I want to verify that I am on the correct page by checking the page title and heading.

**Acceptance Criteria:**

- The browser tab should display the title "Kubernetes vs Docker."

- The heading on the page should read "Kubernetes vs Docker."

- Key concepts like "Kubernetes" and "Docker" should be clearly visible and explained in comparison.
