### ISSUE TITLE
Scaling Strategies MD (Hexo)

### ISSUE THREAD

**Issue by Anneryshc** [Anneryshc/is373_devops_hexo#14]
Add links and information.

**Comment by jar285** [comment]
## 1.6 Epic 6: Scaling Strategies + Criteria
### 1.6.1 Story 1 + Acceptance Criteria:
* As a student, I want to access the Scaling Strategies page and learn about scaling in cloud environments.
**Acceptance Criteria:**

* The main index or glossary should contain a link to the Scaling Strategies page.
* The link must be visible and functional.

## 1.6.2 Story 2 + Acceptance Criteria:
* As a student, I want to confirm that I am on the Scaling Strategies page.
**Acceptance Criteria:**

* The browser tab should show the title “Scaling Strategies.”
* The heading on the page must read “Scaling Strategies.”
* Key concepts like “Vertical Scaling” and “Horizontal Scaling” should be visible and clearly explained.
