### ISSUE TITLE
Orchestration and Container Management MD (Hexo)

### ISSUE THREAD

**Issue by Anneryshc** [Anneryshc/is373_devops_hexo#15]
Add links and information.

**Comment by jar285** [comment]
## 1.5 Epic 5: Orchestration and Container Management + Criteria
### 1.5.1 Story 1 + Criteria:
* As a student, I want to access the Orchestration and Container Management page to understand how to manage containers in production.

**Acceptance Criteria:**

* The index or glossary should have a working link leading to the Orchestration and Container Management page.
* The link must be visible and functional.
### 1.5.2 Story 2 + Criteria:
* As a student, I want to make sure that the page content for Orchestration and Container Management is clear and correct.

**Acceptance Criteria:**

* The page title should mention "Orchestration and Container Management."
* The heading must read “Orchestration and Container Management.”
* Concepts like "Orchestration" and "Container Management" should be clearly defined and explained.
