### ISSUE TITLE
The Twelve-Factor App MD (Hexo)

### ISSUE THREAD

**Issue by Anneryshc** [Anneryshc/is373_devops_hexo#16]
Add links and information.

**Comment by jar285** [comment]
## 1.3 Epic 3: The Twelve-Factor App + Criteria
### 1.3.1 Story 1 + Criteria:
* As a student, I want to be able to access The Twelve-Factor App documentation page from the index.

**Acceptance Criteria:**

* The index should have a link that leads to The Twelve-Factor App page.
* The link must be visible and functional.

### 1.3.2 Story 2 + Criteria:
* As a student, I want to confirm that I am reading The Twelve-Factor App page.

**Acceptance Criteria:**

* The page title (browser tab) should contain "Twelve-Factor App."
* The heading on the page should read "The Twelve-Factor App."
* Contain straightforward information about the Twelve-Factor App.
