### ISSUE TITLE
 Software Packaging MD (Hexo)

### ISSUE THREAD

**Issue by Anneryshc** [Anneryshc/is373_devops_hexo#17]
Add links and information.

**Comment by jar285** [comment]
## 1.8 Epic 8: Software Packaging + Criteria
### 1.8.1 Story 1 + Criteria:
* As a student, I want to access the Software Packaging page to understand how applications and their dependencies are bundled for consistent execution.

**Acceptance Criteria:**

* The index or glossary should have a clearly visible and functional link to the Software Packaging page.
* The link must direct the user to the appropriate page.


## 1.8.2 Story 2 + Criteria:
* As a student, I want to confirm that the Software Packaging page accurately describes the software bundling process.
**Acceptance Criteria:**

* The browser tab should display “Software Packaging.”
* The page heading should read “Software Packaging.”
* The page should include explanations about key concepts like "Dependency Management" and "Portable Applications."
