### ISSUE TITLE
History of Virtualization MD (Hexo)

### ISSUE THREAD

**Issue by Anneryshc** [Anneryshc/is373_devops_hexo#18]
Add links and information

**Comment by jar285** [comment]
## 1.7 Epic 7: History of Virtualization + Criteria
### 1.7.1 Story 1 + Acceptance Criteria:
* As a student, I want to access the History of Virtualization page to learn how virtualization technologies evolved.
**Acceptance Criteria:**

* The index or glossary must contain a working link to the History of Virtualization page.
* The link must be visible and functional.


### 1.7.2 Story 2 + Acceptance Criteria:
* As a student, I want to ensure that the content on the History of Virtualization page is correct and informative.
**Acceptance Criteria:**

* The browser tab should display “History of Virtualization.”
* The page heading must read “History of Virtualization.”
* The page should detail key points in virtualization history, from the 1960s to the present day.
