### ISSUE TITLE
Resources MD (Hexo)

### ISSUE THREAD

**Issue by Anneryshc** [Anneryshc/is373_devops_hexo#19]
Add links and information

**Comment by jar285** [comment]
## 1.9 Epic 9: Resources + Criteria
### 1.9.1 Story 1 + Criteria:

- As a student, I want to access the Resources page to find useful links and articles on DevOps topics like Docker, Virtualization, and Scaling.

**Acceptance Criteria:**

- The main index should contain a link labeled "Resources" that leads to a page containing curated articles, guides, and tutorials.

- The link must be functional and visible.


### 1.9.2 Story 2 + Criteria:

- As a student, I want to ensure that the links on the Resources page are accessible and relevant.

**Acceptance Criteria:**

- The page title should be “Resources.”

- The heading on the page must read “Resources.”

- All links should open in new tabs and lead to credible, relevant DevOps learning material.
