### ISSUE TITLE
Glossary MD (Hexo)

### ISSUE THREAD

**Issue by Anneryshc** [Anneryshc/is373_devops_hexo#20]
Add links and information

**Comment by jar285** [comment]
## 1.4 Epic 4: Glossary + Criteria
### 1.4.1 Story 1: Access Glossary Page

**Acceptance Criteria**:

- The main index should have a clearly visible and functional link to the Glossary page.

## 1.4.2 Story 2: Verify Glossary Content

**Acceptance Criteria:**

- The browser tab should display the title "Glossary."

- The page must have the heading "Glossary."

- Key terms such as "Containerization," "Docker," and "Virtualization" must be present and properly explained.

## 1.4.3 Story 3: Ensure Links to Key Concepts are Functional

**Acceptance Criteria:**

- Each key term in the Glossary (e.g., "Containerization," "Docker") should have a working link leading to the correct page.

- The links must be functional and clearly visible.
